### ISSUE TITLE
Add in local SQLite database support

### ISSUE THREAD

**Issue by Xslare** [RP-Kit/RPKit#193]
please

**Comment by alyphen** [comment]
Updating database to use jOOQ for SQL code generation. Checklist:
 - [x] auctions
 - [x] banks
 - [x] characters
 - [x] chat
 - [ ] classes
 - [x] core
 - [ ] economy
 - [ ] essentials
 - [ ] experience
 - [ ] feature flags
 - [ ] locks
 - [ ] payments
 - [ ] permissions
 - [x] players
 - [ ] shops
 - [ ] skills
 - [ ] travel
