### ISSUE TITLE
Do you need help?

### ISSUE THREAD

**Issue by gguurr** [RP-Kit/RPKit#401]
Hi its not really an issue but when I looked at the your plugin (and later your pronounces) I thought to my self "they look like a lovely person, I have to reach to them".
So can i help with anything with the RPKit? even if no I really grateful for your plugin and i hope you are doing find in this hard times.
sorry I know its not the place to reach out. anyway good luck and lots of love.

gura (gguurr) she/her/they/them

**Comment by alyphen** [comment]
Hi! Help is always welcome - workspace setup is on the wiki: https://github.com/RP-Kit/RPKit/wiki/Workspace-setup

We have a Discord where most things are discussed, it would be helpful to join: https://discord.com/invite/HdZhTUu

Some easy issues to pick up initially would probably be:

* #168 Lockpicking
* #170 Money top command
* #191 Permission to bypass field hiding
* #209 Add a command to see how long until a piece of food expires

Or if there's anything you think would be useful in the suite to roleplay servers in general, feel free to suggest it by raising an issue.

Let me know if you need a hand with anything!
