### ISSUE TITLE
Health bars 

### ISSUE THREAD

**Issue by Neutonic** [RP-Kit/RPKit#97]
Have a number displayed under everyones MCname i.e 17/20 
Don't have it linked to MC hp so they don't actually die when it hits zero
/damage [player] 5 

Bonus; Have it so only people with permission can see the HP

**Comment by alyphen** [comment]
This is server-specific functionality with little benefit to the wide majority of servers. Each combat plugin will implement its own health mechanic, many of which will simply use Minecraft health. This will be put into imeros-combat, closing for the RPKit repository though.
